// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schema.proto

package v1

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

//
// The Schema object wraps the user's GraphQL Schema, which is stored as an inline string.
// The Schema Object contains a Status field which is used by Qloo to validate the user's input schema.
type Schema struct {
	// Name of the schema. Schema names must be unique
	//
	// Schema Names must be unique and follow the following syntax rules:
	// One or more lowercase rfc1035/rfc1123 labels separated by '.' with a maximum length of 253 characters.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// name of the resolver map to use to resolve this schema.
	// if the user leaves this empty, Qloo will generate the skeleton of a resolver map for the user
	ResolverMap string `protobuf:"bytes,2,opt,name=resolver_map,json=resolverMap,proto3" json:"resolver_map,omitempty"`
	// inline the entire graphql schema as a string here
	InlineSchema string `protobuf:"bytes,3,opt,name=inline_schema,json=inlineSchema,proto3" json:"inline_schema,omitempty"`
	// Status indicates the validation status of the role resource.
	// Status is read-only by clients, and set by gloo during validation
	Status *Status `protobuf:"bytes,6,opt,name=status" json:"status,omitempty" testdiff:"ignore"`
	// Metadata contains the resource metadata for the role
	Metadata *Metadata `protobuf:"bytes,7,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *Schema) Reset()                    { *m = Schema{} }
func (m *Schema) String() string            { return proto.CompactTextString(m) }
func (*Schema) ProtoMessage()               {}
func (*Schema) Descriptor() ([]byte, []int) { return fileDescriptorSchema, []int{0} }

func (m *Schema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Schema) GetResolverMap() string {
	if m != nil {
		return m.ResolverMap
	}
	return ""
}

func (m *Schema) GetInlineSchema() string {
	if m != nil {
		return m.InlineSchema
	}
	return ""
}

func (m *Schema) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Schema) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Schema)(nil), "v1.Schema")
}
func (this *Schema) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Schema)
	if !ok {
		that2, ok := that.(Schema)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.ResolverMap != that1.ResolverMap {
		return false
	}
	if this.InlineSchema != that1.InlineSchema {
		return false
	}
	if !this.Status.Equal(that1.Status) {
		return false
	}
	if !this.Metadata.Equal(that1.Metadata) {
		return false
	}
	return true
}

func init() { proto.RegisterFile("schema.proto", fileDescriptorSchema) }

var fileDescriptorSchema = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0xce, 0x48,
	0xcd, 0x4d, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x94, 0x12, 0x49, 0xcf,
	0x4f, 0xcf, 0x07, 0x73, 0xf5, 0x41, 0x2c, 0x88, 0x8c, 0x14, 0x4f, 0x71, 0x49, 0x62, 0x49, 0x69,
	0x31, 0x94, 0xc7, 0x97, 0x9b, 0x5a, 0x92, 0x98, 0x92, 0x58, 0x02, 0xd5, 0xa7, 0x74, 0x92, 0x91,
	0x8b, 0x2d, 0x18, 0x6c, 0x90, 0x90, 0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02,
	0xa3, 0x06, 0x67, 0x10, 0x98, 0x2d, 0xa4, 0xc8, 0xc5, 0x53, 0x94, 0x5a, 0x9c, 0x9f, 0x53, 0x96,
	0x5a, 0x14, 0x9f, 0x9b, 0x58, 0x20, 0xc1, 0x04, 0x96, 0xe3, 0x86, 0x89, 0xf9, 0x26, 0x16, 0x08,
	0x29, 0x73, 0xf1, 0x66, 0xe6, 0xe5, 0x64, 0xe6, 0xa5, 0xc6, 0x43, 0x1c, 0x24, 0xc1, 0x0c, 0x56,
	0xc3, 0x03, 0x11, 0x84, 0x9a, 0x6d, 0xc9, 0xc5, 0x06, 0x71, 0x86, 0x04, 0x9b, 0x02, 0xa3, 0x06,
	0xb7, 0x11, 0x97, 0x5e, 0x99, 0xa1, 0x5e, 0x30, 0x58, 0xc4, 0x49, 0xf4, 0xd3, 0x3d, 0x79, 0xc1,
	0x92, 0xd4, 0xe2, 0x92, 0x94, 0xcc, 0xb4, 0x34, 0x2b, 0xa5, 0xcc, 0xf4, 0xbc, 0xfc, 0xa2, 0x54,
	0xa5, 0x20, 0xa8, 0x06, 0x21, 0x0d, 0x2e, 0x0e, 0x98, 0x9b, 0x25, 0xd8, 0xc1, 0x9a, 0x79, 0x40,
	0x9a, 0x7d, 0xa1, 0x62, 0x41, 0x70, 0x59, 0x27, 0x96, 0x15, 0x8f, 0xe4, 0x18, 0x93, 0xd8, 0xc0,
	0x1e, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x50, 0x46, 0x93, 0x20, 0x01, 0x00, 0x00,
}
