/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	scheme "github.com/solo-io/qloo/pkg/storage/crd/client/clientset/versioned/scheme"
	v1 "github.com/solo-io/qloo/pkg/storage/crd/solo.io/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResolverMapsGetter has a method to return a ResolverMapInterface.
// A group's client should implement this interface.
type ResolverMapsGetter interface {
	ResolverMaps(namespace string) ResolverMapInterface
}

// ResolverMapInterface has methods to work with ResolverMap resources.
type ResolverMapInterface interface {
	Create(*v1.ResolverMap) (*v1.ResolverMap, error)
	Update(*v1.ResolverMap) (*v1.ResolverMap, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.ResolverMap, error)
	List(opts meta_v1.ListOptions) (*v1.ResolverMapList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ResolverMap, err error)
	ResolverMapExpansion
}

// resolverMaps implements ResolverMapInterface
type resolverMaps struct {
	client rest.Interface
	ns     string
}

// newResolverMaps returns a ResolverMaps
func newResolverMaps(c *QlooV1Client, namespace string) *resolverMaps {
	return &resolverMaps{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the resolverMap, and returns the corresponding resolverMap object, and an error if there is any.
func (c *resolverMaps) Get(name string, options meta_v1.GetOptions) (result *v1.ResolverMap, err error) {
	result = &v1.ResolverMap{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resolvermaps").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResolverMaps that match those selectors.
func (c *resolverMaps) List(opts meta_v1.ListOptions) (result *v1.ResolverMapList, err error) {
	result = &v1.ResolverMapList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resolvermaps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resolverMaps.
func (c *resolverMaps) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resolvermaps").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a resolverMap and creates it.  Returns the server's representation of the resolverMap, and an error, if there is any.
func (c *resolverMaps) Create(resolverMap *v1.ResolverMap) (result *v1.ResolverMap, err error) {
	result = &v1.ResolverMap{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resolvermaps").
		Body(resolverMap).
		Do().
		Into(result)
	return
}

// Update takes the representation of a resolverMap and updates it. Returns the server's representation of the resolverMap, and an error, if there is any.
func (c *resolverMaps) Update(resolverMap *v1.ResolverMap) (result *v1.ResolverMap, err error) {
	result = &v1.ResolverMap{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resolvermaps").
		Name(resolverMap.Name).
		Body(resolverMap).
		Do().
		Into(result)
	return
}

// Delete takes name of the resolverMap and deletes it. Returns an error if one occurs.
func (c *resolverMaps) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resolvermaps").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resolverMaps) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resolvermaps").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched resolverMap.
func (c *resolverMaps) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.ResolverMap, err error) {
	result = &v1.ResolverMap{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resolvermaps").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
